services:
  frontend:
    build:
      context: .
      target: dev-envs
    container_name: frontend
    ports:
      - '80:4200'
      - '4200:4200'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
